# The Multi-Dimensional Mirror

The world was created in dialogue between the Mirror (God) and the Reflection (the material world).

Reality consists primarily as a reflection of consciousness in the dual-mirror that is comprised of the physical and metaphysical realms. On either side of the dual-mirror, there are four elements: Reason (logic), Soul (heart), Action (inner intention), and Passivity (outer intention).

Reason and Action relate to the physical world.

Soul and Passivity relate to the metaphysical world.

The world we experience agrees with us and dodges us at the same time. In other words, it acts like a mirror. It literally reflects all our notions of reality, whatever they may be.

There's no point in searching for an absolute truth. Like Kierkegaard said, truth is subjectivity. It's better to accept that reality is a dual mirror. It has a physical aspect, the material world, and a metaphysical aspect, the non-physical realm which exists beyond the limits of our five-sensory perception but is as objectively real as the material world.


# Alternatives Space aka the Variants Space

*Every theory represents a separate aspect of a multi-faceted reality.*

*Reality manifests itself in an infinite variety of forms.*

The **alternatives space** is an infinite field containing information on all possible scenarios of any event that could ever possibly take place. 

*It serves as a template or coordinate grid for the movement of all matter in time and space.*

Time is static until we look at each frame (instance in time) in sequence.

Countless alternatives of each of our fates exist simultaneously in stasis. 

*Thought energy transforms one of the possible alternatives into physical reality.*

When energy passes through the human body, it is modified by that person's thoughts.

Whenever you think about something, be it positive or negative, you are radiating thought energy into the alternatives space. This has the effect of introducing corresponding changes into your life.

The infinity of worlds within worlds exists simultanously.

In Transurfing, we can choose our happiness; we do not have to fight to get it. Whatever we *order*, our choice is granted unconditionally. 
